#!/bin/bash

if ! whoami |grep -q icpc; then
  printf "This is user '%s', you should run this script as user 'icpc'\n" "${USER}"
  exit 1
fi

FIFO="/dev/shm/icpc-clean-homed.fifo"

if [[ ! -e "$FIFO" ]]; then
  echo "FIFO does not exist, daemon is not running"
  echo "Unrepairable error"
  exit 4
fi

echo cleannow > /dev/shm/icpc-clean-homed.fifo

exit 0
